FROM pytorch/pytorch:0.4_cuda9_cudnn7
MAINTAINER Louis Tiao <louistiao@me.com>

RUN git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix && \
    cd pytorch-CycleGAN-and-pix2pix && \
    pip install --no-cache-dir -r requirements.txt
